# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DecryptAndEncrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(558, 271)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 134, 170))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdoAes = QtWidgets.QRadioButton(self.groupBox)
        self.rdoAes.setObjectName("rdoAes")
        self.verticalLayout.addWidget(self.rdoAes)
        self.rdoDes = QtWidgets.QRadioButton(self.groupBox)
        self.rdoDes.setObjectName("rdoDes")
        self.verticalLayout.addWidget(self.rdoDes)
        self.rdoTripleDes = QtWidgets.QRadioButton(self.groupBox)
        self.rdoTripleDes.setObjectName("rdoTripleDes")
        self.verticalLayout.addWidget(self.rdoTripleDes)
        self.rdoRSA = QtWidgets.QRadioButton(self.groupBox)
        self.rdoRSA.setObjectName("rdoRSA")
        self.verticalLayout.addWidget(self.rdoRSA)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 0, 381, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 91, 22))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 22))
        self.label.setObjectName("label")
        self.txtOutputFile = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtOutputFile.setGeometry(QtCore.QRect(20, 130, 191, 28))
        self.txtOutputFile.setObjectName("txtOutputFile")
        self.txtInputFile = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtInputFile.setGeometry(QtCore.QRect(20, 60, 191, 28))
        self.txtInputFile.setObjectName("txtInputFile")
        self.btnOpen = QtWidgets.QPushButton(self.groupBox_2)
        self.btnOpen.setGeometry(QtCore.QRect(240, 60, 93, 32))
        self.btnOpen.setObjectName("btnOpen")
        self.btnSaveAs = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSaveAs.setGeometry(QtCore.QRect(240, 130, 93, 32))
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(150, 210, 93, 32))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(310, 210, 93, 32))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnGenRSA = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenRSA.setGeometry(QtCore.QRect(450, 210, 93, 32))
        self.btnGenRSA.setObjectName("btnGenRSA")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Algorithms"))
        self.rdoAes.setText(_translate("MainWindow", "AES"))
        self.rdoDes.setText(_translate("MainWindow", "DES"))
        self.rdoTripleDes.setText(_translate("MainWindow", "Triple DES"))
        self.rdoRSA.setText(_translate("MainWindow", "RSA"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Files"))
        self.label_2.setText(_translate("MainWindow", "Output File"))
        self.label.setText(_translate("MainWindow", "Input File"))
        self.btnOpen.setText(_translate("MainWindow", "📁 Open"))
        self.btnSaveAs.setText(_translate("MainWindow", "💾 Save as"))
        self.btnEncrypt.setText(_translate("MainWindow", "🔒Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "🔓Decrypt"))
        self.btnGenRSA.setText(_translate("MainWindow", "🔑Gen RSA"))
