# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 386)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_verify = QtWidgets.QPushButton(self.centralwidget)
        self.button_verify.setGeometry(QtCore.QRect(360, 270, 100, 38))
        self.button_verify.setObjectName("button_verify")
        self.button_generate = QtWidgets.QPushButton(self.centralwidget)
        self.button_generate.setGeometry(QtCore.QRect(350, 20, 100, 38))
        self.button_generate.setObjectName("button_generate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(76, 90, 91, 22))
        self.label_4.setObjectName("label_4")
        self.txt_infomation_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_infomation_text.setGeometry(QtCore.QRect(180, 90, 281, 61))
        self.txt_infomation_text.setStyleSheet("QTextEdit {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.txt_infomation_text.setObjectName("txt_infomation_text")
        self.txt_signature_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_signature_text.setGeometry(QtCore.QRect(180, 180, 281, 61))
        self.txt_signature_text.setStyleSheet("QTextEdit {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.txt_signature_text.setObjectName("txt_signature_text")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(86, 180, 81, 22))
        self.label_5.setObjectName("label_5")
        self.button_sign = QtWidgets.QPushButton(self.centralwidget)
        self.button_sign.setGeometry(QtCore.QRect(180, 270, 100, 38))
        self.button_sign.setObjectName("button_sign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_verify.setText(_translate("MainWindow", "Verify"))
        self.button_generate.setText(_translate("MainWindow", "Generate"))
        self.label_2.setText(_translate("MainWindow", "ECC CIPHER"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.button_sign.setText(_translate("MainWindow", "Sign"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
