# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 90, 67, 22))
        self.label.setObjectName("label")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(120, 90, 281, 61))
        self.txt_plain_text.setStyleSheet("QTextEdit {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.button_generate = QtWidgets.QPushButton(self.centralwidget)
        self.button_generate.setGeometry(QtCore.QRect(620, 10, 100, 38))
        self.button_generate.setObjectName("button_generate")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(120, 180, 281, 61))
        self.txt_cipher_text.setStyleSheet("QTextEdit {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(26, 180, 81, 22))
        self.label_3.setObjectName("label_3")
        self.txt_infomation_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_infomation_text.setGeometry(QtCore.QRect(560, 90, 281, 61))
        self.txt_infomation_text.setStyleSheet("QTextEdit {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.txt_infomation_text.setObjectName("txt_infomation_text")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(456, 90, 91, 22))
        self.label_4.setObjectName("label_4")
        self.txt_signature_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_signature_text.setGeometry(QtCore.QRect(560, 180, 281, 61))
        self.txt_signature_text.setStyleSheet("QTextEdit {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.txt_signature_text.setObjectName("txt_signature_text")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(466, 180, 81, 22))
        self.label_5.setObjectName("label_5")
        self.button_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.button_encrypt.setGeometry(QtCore.QRect(120, 270, 100, 38))
        self.button_encrypt.setObjectName("button_encrypt")
        self.button_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.button_decrypt.setGeometry(QtCore.QRect(300, 270, 100, 38))
        self.button_decrypt.setObjectName("button_decrypt")
        self.button_sign = QtWidgets.QPushButton(self.centralwidget)
        self.button_sign.setGeometry(QtCore.QRect(560, 270, 100, 38))
        self.button_sign.setObjectName("button_sign")
        self.button_verify = QtWidgets.QPushButton(self.centralwidget)
        self.button_verify.setGeometry(QtCore.QRect(740, 270, 100, 38))
        self.button_verify.setObjectName("button_verify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 977, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Plain Text"))
        self.label_2.setText(_translate("MainWindow", "RSA CIPHER"))
        self.button_generate.setText(_translate("MainWindow", "Generate"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.button_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.button_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.button_sign.setText(_translate("MainWindow", "Sign"))
        self.button_verify.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
